spring.application.name=api-gateway-service
server.port=8080

# Classes Management Service Route
spring.cloud.gateway.routes[0].id=classes-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/classes/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/classes(?<segment>/?.*), /classes$\{segment}

# Equipment Management Service Route
spring.cloud.gateway.routes[1].id=equipment-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/equipment/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/equipment(?<segment>/?.*), /equipment$\{segment}

# Members Management Service Route
spring.cloud.gateway.routes[2].id=members-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/members/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/members(?<segment>/?.*), /members$\{segment}

# Trainers Management Service Route
spring.cloud.gateway.routes[3].id=trainers-service
spring.cloud.gateway.routes[3].uri=http://localhost:8100
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/trainers/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/api/trainers(?<segment>/?.*), /trainer$\{segment}
