spring.application.name=api-gateway-service
server.port=9000
spring.main.allow-bean-definition-overriding=true
spring.main.web-application-type=reactive
spring.cache.type=none
spring.cloud.loadbalancer.cache.enabled=false
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.org.springframework.cloud.loadbalancer.core=TRACE
logging.level.org.springframework.cloud.client.loadbalancer=TRACE

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Keycloak and JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/gimnasio
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak.auth-server-url=http://localhost:8080/auth
keycloak.realm=gimnasio
keycloak.resource=api-gateway
keycloak.public-client=false
keycloak.credentials.secret=EMP8Bf1JeebQF7LmohnirhR0ZMdlfTBl
logging.level.org.springframework.security=DEBUG

# OpenAPI/Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.urls[0].name=Classes Management
springdoc.swagger-ui.urls[0].url=/api/classes/v3/api-docs
springdoc.swagger-ui.urls[1].name=Equipment Management
springdoc.swagger-ui.urls[1].url=/api/equipment/v3/api-docs
springdoc.swagger-ui.urls[2].name=Members Management
springdoc.swagger-ui.urls[2].url=/api/members/v3/api-docs
springdoc.swagger-ui.urls[3].name=Trainers Management
springdoc.swagger-ui.urls[3].url=/api/trainers/v3/api-docs