spring.application.name=api-gateway-service
server.port=9000

# Classes Management Service Route
spring.cloud.gateway.routes[0].id=classes-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/classes/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/classes(?<segment>/?.*), /classes$\{segment}

# Equipment Management Service Route
spring.cloud.gateway.routes[1].id=equipment-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/equipment/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/equipment(?<segment>/?.*), /equipment$\{segment}

# Members Management Service Route
spring.cloud.gateway.routes[2].id=members-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/members/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/api/members(?<segment>/?.*), /members$\{segment}

# Trainers Management Service Route
spring.cloud.gateway.routes[3].id=trainers-service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/trainers/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/api/trainers(?<segment>/?.*), /trainers$\{segment}

# Keycloak and JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/gimnasio
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak.auth-server-url=http://localhost:8080/auth
keycloak.realm=gimnasio
keycloak.resource=api-gateway
keycloak.public-client=false
keycloak.credentials.secret=EMP8Bf1JeebQF7LmohnirhR0ZMdlfTBl
logging.level.org.springframework.security=DEBUG

# OpenAPI/Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.urls[0].name=Classes Management
springdoc.swagger-ui.urls[0].url=/api/classes/v3/api-docs
springdoc.swagger-ui.urls[1].name=Equipment Management
springdoc.swagger-ui.urls[1].url=/api/equipment/v3/api-docs
springdoc.swagger-ui.urls[2].name=Members Management
springdoc.swagger-ui.urls[2].url=/api/members/v3/api-docs
springdoc.swagger-ui.urls[3].name=Trainers Management
springdoc.swagger-ui.urls[3].url=/api/trainers/v3/api-docs